# action.yml
name: 'Count Lines of Code (cloc)'
description: 'Count Lines of Code with https://github.com/AlDanial/cloc'
outputs:
  lines: # id of output
    description: 'The sum code lines'
runs:
  using: 'docker'
  image: 'Dockerfile'
 
branding:
  icon: 'code'  
  color: 'blue'
